language: python
python:
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install numpy
  - pip install scipy
  - pip install Cython
  - python setup.py install
  - pip install -r requirements-test.txt
script:
  - python -m pytest -s --cov-report term-missing --cov pynanoflann -v
after_success:
  - codecov
